# Use postgres/example user/password credentials
version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - codepod-db-prod:/var/lib/postgresql/data

  api:
    image: codepod-api:v0.0.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - git-data-prod:/srv/git
    command: yarn dev
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      KERNEL_NETWORK: "codepod-prod"

  ui:
    image: codepod-ui:v0.0.1
    restart: always
    command: yarn start

  git-http:
    build: ../dev/docker-git-http
    volumes:
      - git-data-prod:/var/lib/git

  # docker-compose up -d --build --force-recreate --no-deps nginx
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      # I'm mounting this so that I can use webroot method for letsencrypt on
      # the host
      #
      # sudo certbot certonly --webroot /var/www/html
      #
      # only enable when I do the renew
      #
      # - /var/www/html:/var/www/html
    depends_on:
      - ui

  # docker run -it --rm --network host -v $(pwd)/frpc.ini:/etc/frp/frpc.ini snowdreamtech/frpc
  frpc:
    image: snowdreamtech/frpc
    restart: always
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
    network_mode: "host"

volumes:
  codepod-db-prod:
  git-data-prod:

networks:
  default:
    name: codepod-prod
    driver: bridge
